const K = {
  hebrew: [
    // Vowels (Nikud)
    { char: 'בַ', trans: '_', description: 'patach' },
    { char: 'בָ', trans: '+', description: 'qamats' },
    { char: 'בְ', trans: 'i', description: 'shva' },
    { char: 'בֶ', trans: '=', description: 'segol' },
    { char: 'בִ', trans: 'E', description: 'hiriq' },
    { char: 'בֹ', trans: 'O', description: 'holam' },
    { char: 'וּ', trans: 'o', description: 'shuruq' },
    { char: 'בֵ', trans: 'e', description: 'tsere' },
    { char: 'חֲ', trans: '_..', description: 'chataf-patach' },
    { char: 'חֱ', trans: 'E.', description: 'chataf-segol' },
    { char: 'חֳ', trans: 'O_', description: 'hataph-qamats' },
    { char: 'בֻ', trans: 'o_', description: 'kubutz' },
    { char: 'א', trans: 'A', description: 'alef' },
    { char: 'בּ', trans: 'B', description: 'bet' },
    { char: 'ב', trans: 'b', description: 'vet' },
    { char: 'ג', trans: 'G', description: 'gimel' },
    { char: 'ד', trans: 'D', description: 'daled' },
    { char: 'ה', trans: 'H', description: 'hey' },
    { char: 'ו', trans: 'V', description: 'vav' },
    { char: 'ז', trans: 'X', description: 'tsayin' },
    { char: 'ח', trans: 'K', description: 'chet' },
    { char: 'ת', trans: 'K', description: 'tav (final)' },
    { char: 'ט', trans: 't', description: 'tet' },
    { char: 'י', trans: '\'', description: 'yod' },
    { char: 'כּ', trans: 'C', description: 'kaf' },
    { char: 'כ', trans: 'c', description: 'kof' },
    { char: 'ך', trans: 'C', description: 'kaf (final)' },
    { char: 'ל', trans: 'L', description: 'lamed' },
    { char: 'מ', trans: 'M', description: 'mem' },
    { char: 'ם', trans: 'm', description: 'mem (final)' },
    { char: 'נ', trans: 'N', description: 'nun' },
    { char: 'ן', trans: 'N', description: 'nun (final)' },
    { char: 'ס', trans: '$', description: 'samekh' },
    { char: 'ע', trans: 'Y', description: 'ayin' },
    { char: 'פ', trans: 'P', description: 'pe' },
    { char: 'פ', trans: 'p', description: 'ph' },
    { char: 'צ', trans: 'Z', description: 'tzade' },
    { char: 'ץ', trans: 'Z', description: 'tzade (final)' },
    { char: 'ק', trans: 'Q', description: 'qof' },
    { char: 'ר', trans: 'R', description: 'resh' },
    { char: 'ש', trans: 'S', description: 'shin' },
    { char: 'ש', trans: 's', description: 'sin' },
    { char: 'ת', trans: 'T', description: 'tav' }
  ],
}


export default K